# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='youtube/images/')),
                ('url', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=500)),
            ],
        ),
    ]
