# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ub_img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
