# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_video_ub_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='ub_img',
            new_name='ubimg',
        ),
    ]
